SELECT FILE_ID, FILE_NAME, FILE_TYPE, TABLESPACE_NAME, FREE_EXTENTS,
       TOTAL_EXTENTS,  EXTENT_SIZE, INITIAL_SIZE, MAXIMUM_SIZE, AUTOEXTEND_SIZE, DATA_FREE, STATUS ENGINE
       FROM INFORMATION_SCHEMA.FILES 
       WHERE TABLESPACE_NAME LIKE 'innodb_system' ;

SELECT LOGFILE_GROUP_NAME, FILE_NAME, EXTRA,TABLESPACE_NAME,FILE_TYPE
FROM INFORMATION_SCHEMA.FILES
WHERE  FILE_TYPE = 'DATAFILE';

select * from INFORMATION_SCHEMA.USER_PRIVILEGES

SELECT FILE_NAME, LOGFILE_GROUP_NUMBER, EXTRA
FROM INFORMATION_SCHEMA.FILES;

select * from INFORMATION_SCHEMA.tablespaces;
select * from INFORMATION_SCHEMA.INNODB_SYS_TABLESPACES;
select * from INFORMATION_SCHEMA.USER_PRIVILEGES;
select * from INFORMATION_SCHEMA.INNODB_SYS_TABLESPACES;
select * from INFORMATION_SCHEMA.ENGINES;
select * from INFORMATION_SCHEMA.TABLES where engine not in ('MEMORY','InnoDB');
select * from INFORMATION_SCHEMA.SESSION_VARIABLES;
select * from mysql.user;
select * from mysql.db;

select * from INFORMATION_SCHEMA.SCHEMATA;                             |
select * from INFORMATION_SCHEMA.SCHEMA_PRIVILEGES where table_schema='test';

select * from INFORMATION_SCHEMA.SCHEMA_PRIVILEGES;
select * from INFORMATION_SCHEMA.PROFILING;
select * from INFORMATION_SCHEMA.COLLATIONS where collation_name like '%utf8%';
select * from INFORMATION_SCHEMA.parameters;


